
volumes:
  geoserver-data-dir-one:
  geoserver-data-dir-two:
  geoserver-data-dir-three:


services:
  geoserver_one:
    image: 'kartoza/geoserver:${TAG:-manual-build}'
    restart: 'always'
    volumes:
      - geoserver-data-dir-one:/opt/geoserver/data_dir
      - ./tests:/tests
      - ./assets/logging.xml:/opt/geoserver/data_dir/logging.xml
    environment:
      GEOSERVER_ADMIN_PASSWORD: myawesomegeoserver
      GEOSERVER_ADMIN_USER: admin
      EXPECTED_LOGGING_PROFILE: GEOSERVER_DEVELOPER_LOGGING
      INITIAL_MEMORY: 2G
      MAXIMUM_MEMORY: 4G
      CONTAINER_NAME: geoserver_one
      CONSOLE_HANDLER_LEVEL: WARNING
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$${GEOSERVER_ADMIN_PASSWORD} http://localhost:8080/geoserver/rest/about/version.xml"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  geoserver_two:
    image: 'kartoza/geoserver:${TAG:-manual-build}'
    restart: 'always'
    volumes:
      - geoserver-data-dir-two:/opt/geoserver/data_dir
      - ./tests:/tests
    environment:
      GEOSERVER_ADMIN_PASSWORD: myawesomegeoserver
      GEOSERVER_ADMIN_USER: admin
      GEOSERVER_LOG_PROFILE: VERBOSE_LOGGING
      EXPECTED_LOGGING_PROFILE: VERBOSE_LOGGING
      INITIAL_MEMORY: 2G
      MAXIMUM_MEMORY: 4G
      CONTAINER_NAME: geoserver_two
      CONSOLE_HANDLER_LEVEL: WARNING
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$$(cat /opt/geoserver/data_dir/security/pass.txt) http://localhost:8080/geoserver/rest/about/version.xml"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  geoserver_three:
    image: 'kartoza/geoserver:${TAG:-manual-build}'
    restart: 'always'
    volumes:
      - geoserver-data-dir-three:/opt/geoserver/data_dir
      - ./tests:/tests
    environment:
      GEOSERVER_ADMIN_PASSWORD: myawesomegeoserver
      GEOSERVER_ADMIN_USER: admin
      EXPECTED_LOGGING_PROFILE: DEFAULT_LOGGING
      INITIAL_MEMORY: 2G
      MAXIMUM_MEMORY: 4G
      CONTAINER_NAME: geoserver_three
      CONSOLE_HANDLER_LEVEL: WARNING
    ports:
      - "8083:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$$(cat /opt/geoserver/data_dir/security/pass.txt) http://localhost:8080/geoserver/rest/about/version.xml"]
      interval: 1m30s
      timeout: 10s
      retries: 3

