volumes:
   geoserver-data:
   geo-db-data:
   geoserver-gwc:
   geoserver-settings:

networks:
   traefik-public:
     external: true
   internal:
     driver: bridge

services:
   db:
      image: kartoza/postgis:${POSTGIS_VERSION_TAG}
      volumes:
        - geo-db-data:/var/lib/postgresql
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - ALLOW_IP_RANGE=${ALLOW_IP_RANGE}
        - FORCE_SSL=TRUE
      restart: on-failure
      networks:
        - internal
      healthcheck:
        test: "pg_isready -h 127.0.0.1 -U ${POSTGRES_USER}"
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 1m

   geoserver:
      image: kartoza/geoserver:${GS_VERSION}
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - geoserver-gwc:/opt/geoserver/gwc
        - geoserver-settings:/settings
      #ports:
       # - "${GEOSERVER_PORT}:8080"
      restart: on-failure
      environment:
        - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
        - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
        - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
        - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
        - INITIAL_MEMORY=${INITIAL_MEMORY}
        - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
        - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
        - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
        - GEOSERVER_CONTEXT_ROOT=${GEOSERVER_CONTEXT_ROOT}
        - ROOT_WEBAPP_REDIRECT=true
        - CONSOLE_HANDLER_LEVEL=${CONSOLE_HANDLER_LEVEL}
        - PROXY_BASE_URL=https://gis.rabciak.site/geoserver
        - GEOSERVER_CSRF_WHITELIST=gis.rabciak.site
        - HTTP_SCHEME=https
        - HTTP_PROXY_NAME=gis.rabciak.site
        - HTTP_PROXY_PORT=443
      depends_on:
        db:
          condition: service_healthy
      networks:
        - internal
        - traefik-public
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.geoserver.rule=Host(`gis.rabciak.site`)
        - traefik.http.routers.geoserver.tls=true
        - traefik.http.routers.geoserver.entrypoints=web,websecure
        - traefik.http.routers.geoserver.tls.certresolver=mytlschallenge
        - traefik.http.services.geoserver.loadbalancer.server.port=8080
        - traefik.http.services.geoserver.loadbalancer.server.scheme=http
        - traefik.http.services.geoserver.loadbalancer.passhostheader=true
        - traefik.http.routers.geoserver.middlewares=geoserver-headers
        - traefik.http.middlewares.geoserver-headers.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.middlewares.geoserver-headers.headers.customrequestheaders.X-Forwarded-Port=443
      healthcheck:
        test: [ "CMD-SHELL", "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null -u $${GEOSERVER_ADMIN_USER}:$${GEOSERVER_ADMIN_PASSWORD} http://localhost:8080/geoserver/rest/about/version.xml" ]
        interval: 1m30s
        timeout: 10s
        retries: 3
        start_period: 1m

